### ISSUE TITLE
Remove returnFormat prop from DatePicker

### ISSUE THREAD

**Issue by veej** [buildo/react-components#1347]
@gabro is proposing to remove `returnFormat` (and `T`s other than `Date`) completely

_Originally posted by @giogonzo in https://github.com/buildo/react-components/pull/1333_

**Comment by gabro** [comment]
My proposal is a bit more radical:

- remove parametricity from `DatePicker` and use `Date` as input (`value`, `defaultValue`) and output (`onChange`). We can keep using moment internally, since react-dates uses it

- remove `returnFormat`: it seems a mix of concerns, the DatePicker should consume and yield values, whereas the presentation of those values should be handled separately

- remove `onClear` and just return `onChange(value: Date | null)` I'm not sure of what's the value of having `onClear` and it complicates the logic (especially in the date range picker I'm working on)
