### ISSUE TITLE
CHANGELOG is out of date

### ISSUE THREAD

**Issue by giogonzo** [buildo/react-components#1441]
https://github.com/buildo/react-components/blob/master/CHANGELOG.md is last updated 8 months ago

**Comment by aSlug** [comment]
Doesn't `smooth-release` create the changelog at every release? 🤔

**Comment by giogonzo** [comment]
It's supposed to, but that's not happening, not sure why

**Comment by aSlug** [comment]
The `release-version` script is explicitly declaring the tasks to be ran, and `changelog` task is not included. Since this script has not been changed recently and also looking at the commit history I can assume that the changelog has never been generated running `release-version` script.

@gabro was the generation of changelog part of some CI that is not active any more?

**Comment by gabro** [comment]
mm, maybe a long time ago, I've always assumed that smooth-release would take of it. It's definitely not, now
