### ISSUE TITLE
[TextOverflow] - treats not overflowed text as such

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#346]
## description
- this one has correctly a tooltip

[![https://gyazo.com/6b5a2603efe6ae16ed7b105a6eb799a8](https://i.gyazo.com/6b5a2603efe6ae16ed7b105a6eb799a8.gif)](https://gyazo.com/6b5a2603efe6ae16ed7b105a6eb799a8)

- but this one shouldn't

[![https://gyazo.com/05866011d6b8e63310bc6471b7cf05fd](https://i.gyazo.com/05866011d6b8e63310bc6471b7cf05fd.gif)](https://gyazo.com/05866011d6b8e63310bc6471b7cf05fd)

**Comment by FrancescoCioria** [comment]
I think we should revert #107 

/cc @giogonzo

**Comment by francescogior** [comment]
Well, going back before #107, it happens that actually some overflowed text is treated as not-overflowed

![](https://i.gyazo.com/55158402095e7b169ea07bbfaf1a5b2e.gif)

**Comment by giogonzo** [comment]
:confused:

**Comment by FrancescoCioria** [comment]
WAT? :cry:

**Comment by FrancescoCioria** [comment]
recap (for Chrome)
let's take this situation:
- container has `max-width: 100px`
- string1 is 50px wide
- string2 is 100px wide
- string3 is 150px wide

1. container + string1
- container is 50px wide
- no ellipsis
- string and container have same width
2. container + string2
- container is 100px wide
- ellpisis
- string and container have same width
3. container + string3
- container is 100px wide
- ellipsis
- string and container have different width

as you can see the problem is we have with case 1 and 2 as in both case we have "string and container have same width" but in the second one, for some reason, Chrome is showing the text with ellipsis

**Comment by nerder** [comment]
This have a very weird behaviour and to me is not about Chrome (or not only at least). As you can see in this [jsFiddle](http://jsfiddle.net/vNRpw/381/) using vanilla javascript we have a different behaviour.

1. container + string1
  - container is 207px wide
  - no ellipsis
  - string and container have same width
2. container + string2
  - container is 206px wide
  - no ellipsis
  - string and container have same width
3. container + string3
  - container is 205px wide
  - ellipsis
  - string and container have different width

This needs further investigation but sounds like pain IMHO
