### ISSUE TITLE
New tablo component

### ISSUE THREAD

**Issue by veej** [buildo/react-components#651]
## requirements

The new `Tablo` component will replace the `Table` wrapper in the next future.

`Tablo` is essentially a cleaned and improved version of `Table`, based on [`fixed-data-table-2`](https://github.com/schrodinger/fixed-data-table-2), with new, modular, features (i.e. shortcuts, autosize, columns reordering, sorting, ecc.) added around `Table` during the development of our projects.
## specs

{optional: describe technical specs to implement this feature, if not obvious}
## misc

{optional: other useful info}

**Comment by FrancescoCioria** [comment]
> The new Tablo component will replace the Table wrapper in the next future.

Just pointing one thing
IMO we may completely replace `Table` only when we prove that `Tablo` is as performant as `Table`: there may be some performance issues in current implementation. If yes we must solve them before backporting it (we use `fixed-data-table` **only** because it has great performances :) )

**Comment by veej** [comment]
Of course @FrancescoCioria, performance evaluation is something we must do for sure. At a first moment, `Table` and `Tablo` will coexist, till we're sure we can switch without any hassle.

In this respect, I must address an issue with sub-component name collisions (e.g. `Column`). Since in `src/index.js` we're exporting every component to be used in examples, we should probably find another name for `Tablo/Column`.
