### ISSUE TITLE
Modal: make title prop be `t.ReactChildren`

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#661]
## requirements
modal should allow custom header (title) and not limit the title to be a string.

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
@ascariandrea why?
we made some props limiting with the exact purpose of blocking people from changing the guidelines decided by Alessandra :P

what's the pain point here?
In our idea a title should only be a string, what's your scenario?

**Comment by ascariandrea** [comment]
Look at the modal's header in the gif [here](https://github.com/buildo/lexdoit/pull/1953)

**Comment by FrancescoCioria** [comment]
Sorry, but that doesn't follow our guidelines :)
If you need to do a custom modal you can, of course, but you have to create a custom header.
The default header is not supposed to have a sub-title, nor a button.

The problem I see here is that `Modal` currently always render its own header, this is of course a bug!
We should render header (and footer) only if they have something to render...

So, to recap, I know you're blocked by `t.String` and that because of it you have to work more, but that's exactly **why** we put `t.String` :)

**Comment by ascariandrea** [comment]
Ok, it was clear I didn't have any clue on the guidelines we built :)
